# Aghost gear

- type: startingGear
  id: MobAghostGearCarp
  equipment:
    back: ClothingBackpackSatchelAdmin
    belt: ClothingBeltChiefEngineerFilled
    id: AdminPDA
    eyes: ClothingEyesHudMedSec
  storage:
    back:
    - GasAnalyzer
    - AccessConfiguratorUniversal
    - Multitool
    - ToolDebug
    - WelderExperimental
    - RCDExperimental
    - WeaponForceGunAdmin
    - WeaponTetherGunAdmin
    - DoorRemoteAll
    - AnomalyScanner
    - AnomalyLocatorUnpowered
    - AdminHypo
    - SprayPainterRecharging

# Prophunt Gear

- type: startingGear
  id: PropHunterStartingGear
  equipment:
    id: SecPDA
    head: ClothingHeadHelmetBasic
    jumpsuit: ClothingUniformJumpsuitSecurity
    outerClothing: ClothingOuterArmorBasic
    shoes: ClothingShoesBootsJack
    ears: ClothingHeadsetSecurity
    pocket1: FlashlightSeclite
  inhand:
    - ToolboxProphunt

- type: startingGear
  id: PropStartingGear
  equipment:
    id: MimePDA
    ears: ClothingHeadsetService
    mask: ClothingMaskGasSyndicate
    jumpsuit: ClothingUniformMimeJumpsuit
    shoes: ClothingShoesBootsJack
    gloves: ClothingHandsGlovesColorWhite
  inhand:
    - ToolboxProphunt
