- type: gameMapPool
  id: DefaultMapPool
  maps:
  - CarpAmber
  - CarpFeint
  - CarpLampocteis
  - CarpOasis
  - CarpPacked
  - CarpSaltern
  - CarpSparks
  - Bagel
  - Box
  - Elkridge
  - Fland
  - Marathon
  - Plasma
  - Exo
  - Snowball
