- type: gameMapPool
  id: UpstreamMapPool # Carpmosia-edit - Carpmaps
  maps:
  - Bagel
  - Box
  - Elkridge
  - Fland
  - Marathon
  - Oasis
  - Packed
  - Plasma
  - Reach
  - Exo
  - Snowball
  - Serpentcrest
