# Base Mod (for contraband)
- type: entity
  id: BaseSecSuitMod
  parent: [ BaseSuitMod, BaseSecurityContraband ]
  name: suit modkit
  description: A modkit for a standard security hardsuit.
  abstract: true
  components:
  - type: Sprite
    layers:
    - state: base
    - state: overlay-1
      color: "#ec9b2d"
    - state: overlay-2
      color: "#a71010"
    - state: overlay-3
      color: "#eb4c13"
  - type: Tag
    tags:
    - SecurityMod

# Item storage slot
- type: entity
  id: SuitModLongarmSlot
  parent: BaseSecSuitMod
  name: Hardsuit modkit (Longarm-slot)
  components:
  - type: SuitMod
    tags: [ LongarmSlotMod ]
    examineText: suit-mod-longarm-slot
  - type: SuitModSlot
    keys: [ longarm-slot ]
    whitelists:
      - tags:
        - Shotgun
        - Rifle
        - SMG

## Visor mods
- type: entity
  id: SuitModSecVisor
  parent: BaseSecSuitMod
  name: Hardsuit modkit (sec hud)
  components:
  - type: SuitMod
    tags: [ SecurityVisorMod ]
    examineText: suit-mod-sechud
  - type: SuitModHelmet
    componentsToAdd:
    - type: ShowJobIcons
    - type: ShowMindShieldIcons
    - type: ShowCriminalRecordIcons
    - type: ShowContrabandDetails
