- type: loadoutEffectGroup
  id: CompetentService
  effects:
  - !type:JobRequirementLoadoutEffect
    requirement:
      !type:DepartmentTimeRequirement
      department: Civilian
      time: 10h

# Jumpsuit
- type: loadout
  id: ServiceMaidskirt
  effects:
  - !type:GroupLoadoutEffect
    proto: CompetentService
  equipment:
    jumpsuit: ClothingUniformJumpskirtJanimaid

- type: loadout
  id: ServiceMaidskirtMini
  effects:
  - !type:GroupLoadoutEffect
    proto: CompetentService
  equipment:
    jumpsuit: ClothingUniformJumpskirtJanimaidmini

# Shoes
- type: loadout
  id: GaloshesShoes
  equipment:
    shoes: ClothingShoesGaloshes
